### ISSUE TITLE
ERROR 403 login with portal acces from granted customer

### ISSUE THREAD

**Issue by sergioeix** [OCA/server-brand#27]
All sections from customer portal works but not the customer documents (quotations invoices ..) section
Odoo 13 Ubuntu linux multicompany multiwebsite
Solved uninstalling remove_odoo_enterprise.

403: Prohibido
No está autorizado a ver la página que está buscando.

QWeb
Mensaje de Error:

Error to render compiling AST
AccessError: ("Lo sentimos, no tiene permiso para acceder a documentos de tipo 'Módulo' (ir.module.module). Esta operación está permitida para los grupos:\n\t- Administration/Settings - (Operación: read, Usuario: 7)", None)
Template: portal.portal_layout
Path: /t/t/div[2]/div/t[1]/div/div[2]/div[2]/t
Node: <t t-if="request.env['payment.acquirer'].search([('state', 'in', ['enabled', 'test']), ('registration_view_template_id', '!=', False), ('payment_flow', '=', 's2s'), ('company_id', '=', request.env.company.id)])">
                <div class="manage_payment_method mt16"><a href="/my/payment_method">Gestionar métodos de pago</a></div>
            </t>
        
Error ocurrido durante el dibujado de la plantilla portal.portal_layout y evaluando la siguiente expresión: <t t-if="request.env['payment.acquirer'].search([('state', 'in', ['enabled', 'test']), ('registration_view_template_id', '!=', False), ('payment_flow', '=', 's2s'), ('company_id', '=', request.env.company.id)])"> <div class="manage_payment_method mt16"><a href="/my/payment_method">Gestionar métodos de pago</a></div> </t>

Traza
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/opt/odoo13/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f34ca1d8b70>, 7, False, 'ir.module.module', 'read', True, ('es_ES',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_portal_portal_layout_248
  File "<template>", line 2, in body_call_content_246
  File "/opt/odoo13/odoo-custom-addons/remove_odoo_enterprise/models/base.py", line 10, in search
    return super().search(domain, offset, limit, order, count)
  File "/opt/odoo13/odoo/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo13/odoo/odoo/models.py", line 4369, in _search
    query = self._where_calc(args)
  File "/opt/odoo13/odoo/odoo/models.py", line 4098, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo13/odoo/odoo/osv/expression.py", line 674, in __init__
    self.parse()
  File "/opt/odoo13/odoo/odoo/osv/expression.py", line 906, in parse
    right_ids = comodel.with_context(active_test=False).search([('.'.join(path[1:]), operator, right)]).ids
  File "/opt/odoo13/odoo-custom-addons/remove_odoo_enterprise/models/ir_module_module.py", line 9, in search
    return super().search(domain, offset, limit, order, count)
  File "/opt/odoo13/odoo-custom-addons/remove_odoo_enterprise/models/base.py", line 10, in search
    return super().search(domain, offset, limit, order, count)
  File "/opt/odoo13/odoo/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo13/odoo/odoo/models.py", line 4360, in _search
    model.check_access_rights('read')
  File "/opt/odoo13/odoo/odoo/models.py", line 3200, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-23>", line 2, in check
  File "/opt/odoo13/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_model.py", line 1544, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Lo sentimos, no tiene permiso para acceder a documentos de tipo 'Módulo' (ir.module.module). Esta operación está permitida para los grupos:\n\t- Administration/Settings - (Operación: read, Usuario: 7)", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/opt/odoo13/odoo/odoo/http.py", line 804, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 341, in checked_call
    result.flatten()
  File "/opt/odoo13/odoo/odoo/http.py", line 1231, in flatten
    self.response.append(self.render())
  File "/opt/odoo13/odoo/odoo/http.py", line 1224, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 1154, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo13/odoo/addons/website/models/ir_ui_view.py", line 335, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo13/odoo/addons/web_editor/models/ir_ui_view.py", line 25, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 1162, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 334, in _compiled_fn
    raise e
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_portal_portal_my_home_228
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: ("Lo sentimos, no tiene permiso para acceder a documentos de tipo 'Módulo' (ir.module.module). Esta operación está permitida para los grupos:\n\t- Administration/Settings - (Operación: read, Usuario: 7)", None)
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/opt/odoo13/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f34ca1d8b70>, 7, False, 'ir.module.module', 'read', True, ('es_ES',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_portal_portal_layout_248
  File "<template>", line 2, in body_call_content_246
  File "/opt/odoo13/odoo-custom-addons/remove_odoo_enterprise/models/base.py", line 10, in search
    return super().search(domain, offset, limit, order, count)
  File "/opt/odoo13/odoo/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo13/odoo/odoo/models.py", line 4369, in _search
    query = self._where_calc(args)
  File "/opt/odoo13/odoo/odoo/models.py", line 4098, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo13/odoo/odoo/osv/expression.py", line 674, in __init__
    self.parse()
  File "/opt/odoo13/odoo/odoo/osv/expression.py", line 906, in parse
    right_ids = comodel.with_context(active_test=False).search([('.'.join(path[1:]), operator, right)]).ids
  File "/opt/odoo13/odoo-custom-addons/remove_odoo_enterprise/models/ir_module_module.py", line 9, in search
    return super().search(domain, offset, limit, order, count)
  File "/opt/odoo13/odoo-custom-addons/remove_odoo_enterprise/models/base.py", line 10, in search
    return super().search(domain, offset, limit, order, count)
  File "/opt/odoo13/odoo/odoo/models.py", line 1609, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo13/odoo/odoo/models.py", line 4360, in _search
    model.check_access_rights('read')
  File "/opt/odoo13/odoo/odoo/models.py", line 3200, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-23>", line 2, in check
  File "/opt/odoo13/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_model.py", line 1544, in check
    raise AccessError(msg % msg_params)
odoo.exceptions.AccessError: ("Lo sentimos, no tiene permiso para acceder a documentos de tipo 'Módulo' (ir.module.module). Esta operación está permitida para los grupos:\n\t- Administration/Settings - (Operación: read, Usuario: 7)", None)

Error to render compiling AST
AccessError: ("Lo sentimos, no tiene permiso para acceder a documentos de tipo 'Módulo' (ir.module.module). Esta operación está permitida para los grupos:\n\t- Administration/Settings - (Operación: read, Usuario: 7)", None)
Template: portal.portal_layout
Path: /t/t/div[2]/div/t[1]/div/div[2]/div[2]/t
Node: <t t-if="request.env['payment.acquirer'].search([('state', 'in', ['enabled', 'test']), ('registration_view_template_id', '!=', False), ('payment_flow', '=', 's2s'), ('company_id', '=', request.env.company.id)])">
                <div class="manage_payment_method mt16"><a href="/my/payment_method">Gestionar métodos de pago</a></div>
            </t>

**Comment by astirpe** [comment]
@sergioeix I don't know how to reproduce this error, however I fixed a similar error in https://github.com/OCA/server-brand/pull/28. Could you check if that fix is also solving this issue?

**Comment by zackleeuk** [comment]
403: Forbidden
The page you were looking for could not be authorized.

Error message:

Sorry, you are not allowed to access documents of type 'Module' (ir.module.module). This operation is allowed for the groups:
	- Administration/Settings - (Operation: read, User: 4)


this is from shopping cart to register as a new customer and can't go to the payment page.

**Comment by astirpe** [comment]
@zackleeuk I can't reproduce the error. I tried in runbot and also locally. Any extra information on how to reproduce? Could you also try on runbot?

**Comment by zackleeuk** [comment]
Hi,

I will try on runbot and let you know.

**Comment by zackleeuk** [comment]
@astirpe 
tested, all good. many thanks.
