### ISSUE TITLE
[V14] remove_odoo_enterprise when installed causing error, on creation new journal, duplicationg, or importing 

### ISSUE THREAD

**Issue by bunhin** [OCA/server-brand#57]
## Module
remove_odoo_enterprise (i test with V14 )

## Describe the bug
Installing the odoo_enterprise_module has been causing an error when we create a new journal, duplicate a journal, or import journals.

## To Reproduce
1. to intsall the remove_odoo_enterprise module in an existing database
2. Go to Accounting --> Configuration --> Journal
3. Try to create a new journal, duplicate a journal or import journals from a csv/excell file
The error will pop up:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/addons/web/controllers/main.py", line 1394, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14/addons/account/models/account_journal.py", line 397, in copy
    return super(AccountJournal, self).copy(default)
  File "/opt/odoo14/odoo/models.py", line 4680, in copy
    new = self.with_context(lang=None).create(vals)
  File "<decorator-gen-200>", line 2, in create
  File "/opt/odoo14/odoo/api.py", line 326, in _model_create_single
    return create(self, arg)
  File "/opt/odoo14/addons/account/models/account_journal.py", line 555, in create
    journal = super(AccountJournal, self.with_context(mail_create_nolog=True)).create(vals)
  File "<decorator-gen-141>", line 2, in create
  File "/opt/odoo14/odoo/api.py", line 347, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo14/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-68>", line 2, in create
  File "/opt/odoo14/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo14/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo14/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo14/odoo/models.py", line 3876, in create
    records = self._create(data_list)
  File "/opt/odoo14/odoo/models.py", line 4049, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/opt/odoo14/odoo/models.py", line 1266, in _validate_fields
    check(self)
  File "/opt/odoo14/addons/payment/models/account_journal.py", line 13, in _check_journal_type_change
    if acquirer_incompatible_journals and self.env['payment.acquirer'].search_count([('journal_id', 'in', acquirer_incompatible_journals.ids)]):
  File "/opt/odoo14/odoo/models.py", line 1685, in search_count
    res = self.search(args, count=True)
  File "/opt/odoo14/custom-addons/used-addons/remove_odoo_enterprise/models/base.py", line 14, in search
    res = res.filtered(lambda a: not a.module_to_buy)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'int' object has no attribute 'filtered'

4. Uninstall the module
5. Create a new journal again, import or duplicate  ---> Ok, the error is not popping up

6. to isnstall the module remove_odoo_enterprise again --> The error is popping again 

Expected:
The module should not causing such error

**Comment by mariosanroman** [comment]
I have the same problem.
Any workaround or way to fix it?
